extensions:
    dynamicconfig:
        endpoint: 0.0.0.0:55700
        local_config_file: 'schedules.yaml'
        wait_time: 5

receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:55680

exporters:
    logging:

service:
    pipelines:
        metrics:
            receivers: [otlp]
            exporters: [logging]

    extensions: [dynamicconfig]
