codecov:
  require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: yes
