version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - asasalint
    - bodyclose
    - depguard
    - errcheck
    - errorlint
    - godot
    - gosec
    - govet
    - ineffassign
    - misspell
    - perfsprint
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
  settings:
    depguard:
      rules:
        no-sdk-instrumentation:
          files:
            - '**/*/{bridges,instrumentation}/**/*.go'
            - '!$test'
            - "!**/*/bridges/prometheus/*.go" # prometheus bridge is meant to use the SDK
            - "!**/*/instrumentation/runtime/*.go" # runtime instrumentation is meant to use the SDK
            - '!**/*test/*.go'
            - '!**/*test/**/*.go'
            - '!**/*example/*.go'
            - '!**/*example/**/*.go'
          deny:
            - pkg: go.opentelemetry.io/otel/sdk
              desc: Bridges and instrumentations should not use the SDKs, except in test or example modules
        non-tests:
          files:
            - '!$test'
            - '!**/*test/*.go'
          deny:
            - pkg: testing
            - pkg: github.com/stretchr/testify
            - pkg: crypto/md5
            - pkg: crypto/sha1
            - pkg: crypto/**/pkix
    godot:
      exclude:
        # Exclude sentence fragments for lists.
        - ^[ ]*[-•]
        # Exclude sentences prefixing a list.
        - :$
    misspell:
      locale: US
      ignore-rules:
        - cancelled
    perfsprint:
      int-conversion: true
      err-error: true
      errorf: true
      sprintf1: true
      strconcat: true
    revive:
      # Sets the default failure confidence.
      # This means that linting errors with less than 0.8 confidence will be ignored.
      # Default: 0.8
      confidence: 0.01
      rules:
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#blank-imports
        - name: blank-imports
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#bool-literal-in-expr
        - name: bool-literal-in-expr
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#constant-logical-expr
        - name: constant-logical-expr
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#context-as-argument
        # TODO (#2877) re-enable linter when it is compatible. https://github.com/golangci/golangci-lint/issues/3280
        - name: context-as-argument
          disabled: true
          arguments:
            allowTypesBefore: "*testing.T"
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#context-keys-type
        - name: context-keys-type
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#deep-exit
        - name: deep-exit
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#defer
        - name: defer
          disabled: false
          arguments:
            - ["call-chain", "loop"]
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#dot-imports
        - name: dot-imports
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#duplicated-imports
        - name: duplicated-imports
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#early-return
        - name: early-return
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#empty-block
        - name: empty-block
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#empty-lines
        - name: empty-lines
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-naming
        - name: error-naming
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-return
        - name: error-return
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-strings
        - name: error-strings
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#errorf
        - name: errorf
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported
        - name: exported
          disabled: false
          arguments:
            - "sayRepetitiveInsteadOfStutters"
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#flag-parameter
        - name: flag-parameter
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#identical-branches
        - name: identical-branches
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#if-return
        - name: if-return
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#increment-decrement
        - name: increment-decrement
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#indent-error-flow
        - name: indent-error-flow
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#import-shadowing
        - name: import-shadowing
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#package-comments
        - name: package-comments
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#range
        - name: range
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#range-val-in-closure
        - name: range-val-in-closure
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#range-val-address
        - name: range-val-address
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#redefines-builtin-id
        - name: redefines-builtin-id
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#string-format
        - name: string-format
          disabled: false
          arguments:
            - - panic
              - '/^[^\n]*$/'
              - must not contain line breaks
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#struct-tag
        - name: struct-tag
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#superfluous-else
        - name: superfluous-else
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#time-equal
        - name: time-equal
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#var-naming
        - name: var-naming
          disabled: false
          arguments:
            - ["ID"] # AllowList
            - ["Otel", "Aws", "Gcp"] # DenyList
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#var-declaration
        - name: var-declaration
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unconditional-recursion
        - name: unconditional-recursion
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unexported-return
        - name: unexported-return
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unhandled-error
        - name: unhandled-error
          disabled: false
          arguments:
            - "fmt.Fprint"
            - "fmt.Fprintf"
            - "fmt.Fprintln"
            - "fmt.Print"
            - "fmt.Printf"
            - "fmt.Println"
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unnecessary-stmt
        - name: unnecessary-stmt
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#useless-break
        - name: useless-break
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#waitgroup-by-value
        - name: waitgroup-by-value
          disabled: false
    testifylint:
      enable-all: true
      disable:
        - float-compare
        - require-error
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # TODO: Having appropriate comments for exported objects helps development,
      # even for objects in internal packages. Appropriate comments for all
      # exported objects should be added and this exclusion removed.
      - linters:
          - revive
        path: .*internal/.*
        text: exported (method|function|type|const) (.+) should have comment or be unexported
      # Yes, they are, but it's okay in a test.
      - linters:
          - revive
        path: _test\.go
        text: exported func.*returns unexported type.*which can be annoying to use
      # Example test functions should be treated like main.
      - linters:
          - revive
        path: example.*_test\.go
        text: calls to (.+) only in main[(][)] or init[(][)] functions
      # It's okay to not run gosec and perfsprint in a test.
      - linters:
          - gosec
          - perfsprint
          - usestdlibvars
        path: _test\.go
      # Ignoring gosec G402: TLS MinVersion too low
      # as the https://pkg.go.dev/crypto/tls#Config handles MinVersion default well.
      - linters:
          - gosec
        path: config/*.go
        text: 'G402: TLS MinVersion too low.'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - go.opentelemetry.io
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
