// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// DO NOT MODIFY. Generated by gotmpl.
// source: internal/shared/request/resp_writer_wrapper_test.go.tmpl

package request

import (
	"errors"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestRespWriterWriteHeader(t *testing.T) {
	rw := NewRespWriterWrapper(&httptest.ResponseRecorder{}, func(int64) {})

	rw.WriteHeader(http.StatusTeapot)
	assert.Equal(t, http.StatusTeapot, rw.statusCode)
	assert.True(t, rw.wroteHeader)

	rw.WriteHeader(http.StatusGone)
	assert.Equal(t, http.StatusTeapot, rw.statusCode)
}

func TestRespWriterWriteInformationalStatusCode(t *testing.T) {
	rw := NewRespWriterWrapper(&httptest.ResponseRecorder{}, func(int64) {})

	rw.WriteHeader(http.StatusContinue)
	assert.Equal(t, http.StatusOK, rw.statusCode)
	assert.False(t, rw.wroteHeader)

	rw.WriteHeader(http.StatusGone)
	assert.Equal(t, http.StatusGone, rw.statusCode)
	assert.True(t, rw.wroteHeader)
}

func TestRespWriterFlush(t *testing.T) {
	rw := NewRespWriterWrapper(&httptest.ResponseRecorder{}, func(int64) {})

	rw.Flush()
	assert.Equal(t, http.StatusOK, rw.statusCode)
	assert.True(t, rw.wroteHeader)
}

type nonFlushableResponseWriter struct{}

func (nonFlushableResponseWriter) Header() http.Header {
	return http.Header{}
}

func (nonFlushableResponseWriter) Write([]byte) (int, error) {
	return 0, nil
}

func (nonFlushableResponseWriter) WriteHeader(int) {}

func TestRespWriterFlushNoFlusher(t *testing.T) {
	rw := NewRespWriterWrapper(nonFlushableResponseWriter{}, func(int64) {})

	rw.Flush()
	assert.Equal(t, http.StatusOK, rw.statusCode)
	assert.True(t, rw.wroteHeader)
}

func TestConcurrentRespWriterWrapper(t *testing.T) {
	rw := NewRespWriterWrapper(&httptest.ResponseRecorder{}, func(int64) {})

	go func() {
		_, _ = rw.Write([]byte("hello world"))
	}()

	assert.NotNil(t, rw.BytesWritten())
	assert.NotNil(t, rw.StatusCode())
	assert.NoError(t, rw.Error())
}

type errorResponseWriter struct {
	*httptest.ResponseRecorder
	errs []error
}

func (w *errorResponseWriter) Write(p []byte) (int, error) {
	if len(w.errs) > 0 {
		err := w.errs[0]
		w.errs = w.errs[1:]
		return 0, err
	}
	return w.ResponseRecorder.Write(p)
}

func TestRespWriterErrorKeepsFirstError(t *testing.T) {
	first := errors.New("first write failed")
	second := errors.New("second write failed")
	rw := NewRespWriterWrapper(&errorResponseWriter{
		ResponseRecorder: httptest.NewRecorder(),
		errs:             []error{first, second},
	}, func(int64) {})

	_, err := rw.Write([]byte("a"))
	require.ErrorIs(t, err, first)
	_, err = rw.Write([]byte("b"))
	require.ErrorIs(t, err, second)
	assert.ErrorIs(t, rw.Error(), first)
	_, err = rw.Write([]byte("c"))
	require.NoError(t, err)

	assert.ErrorIs(t, rw.Error(), first)
}
