// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// DO NOT MODIFY. Generated by gotmpl.
// source: internal/shared/request/resp_writer_wrapper_test.go.tmpl

package request

import (
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"testing/iotest"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestRespWriterWriteHeader(t *testing.T) {
	rw := NewRespWriterWrapper(&httptest.ResponseRecorder{}, func(int64) {})

	rw.WriteHeader(http.StatusTeapot)
	assert.Equal(t, http.StatusTeapot, rw.statusCode)
	assert.True(t, rw.wroteHeader)

	rw.WriteHeader(http.StatusGone)
	assert.Equal(t, http.StatusTeapot, rw.statusCode)
}

func TestRespWriterWriteInformationalStatusCode(t *testing.T) {
	rw := NewRespWriterWrapper(&httptest.ResponseRecorder{}, func(int64) {})

	rw.WriteHeader(http.StatusContinue)
	assert.Equal(t, http.StatusOK, rw.statusCode)
	assert.False(t, rw.wroteHeader)

	rw.WriteHeader(http.StatusGone)
	assert.Equal(t, http.StatusGone, rw.statusCode)
	assert.True(t, rw.wroteHeader)
}

func TestRespWriterFlush(t *testing.T) {
	rw := NewRespWriterWrapper(&httptest.ResponseRecorder{}, func(int64) {})

	rw.Flush()
	assert.Equal(t, http.StatusOK, rw.statusCode)
	assert.True(t, rw.wroteHeader)
}

type nonFlushableResponseWriter struct{}

func (nonFlushableResponseWriter) Header() http.Header {
	return http.Header{}
}

func (nonFlushableResponseWriter) Write([]byte) (int, error) {
	return 0, nil
}

func (nonFlushableResponseWriter) WriteHeader(int) {}

func TestRespWriterFlushNoFlusher(t *testing.T) {
	rw := NewRespWriterWrapper(nonFlushableResponseWriter{}, func(int64) {})

	rw.Flush()
	assert.Equal(t, http.StatusOK, rw.statusCode)
	assert.True(t, rw.wroteHeader)
}

func TestConcurrentRespWriterWrapper(t *testing.T) {
	rw := NewRespWriterWrapper(&httptest.ResponseRecorder{}, func(int64) {})

	go func() {
		_, _ = rw.Write([]byte("hello world"))
	}()

	assert.NotNil(t, rw.BytesWritten())
	assert.NotNil(t, rw.StatusCode())
	assert.NoError(t, rw.Error())
}

type failOnceResponseWriter struct {
	*httptest.ResponseRecorder
	err error
}

func (w *failOnceResponseWriter) Write(p []byte) (int, error) {
	if err := w.err; err != nil {
		w.err = nil
		return 0, err
	}
	return w.ResponseRecorder.Write(p)
}

func TestRespWriterErrorKeepsFirstError(t *testing.T) {
	want := errors.New("write failed")
	rw := NewRespWriterWrapper(&failOnceResponseWriter{
		ResponseRecorder: httptest.NewRecorder(),
		err:              want,
	}, func(int64) {})

	_, err := rw.Write([]byte("hello"))
	require.ErrorIs(t, err, want)
	_, err = rw.Write([]byte("world"))
	require.NoError(t, err)

	assert.ErrorIs(t, rw.Error(), want)
}

func TestRespWriterReadFrom(t *testing.T) {
	rw := NewRespWriterWrapper(&httptest.ResponseRecorder{}, func(int64) {})

	n, err := rw.ReadFrom(strings.NewReader("hello world"))
	require.NoError(t, err)
	assert.Equal(t, int64(11), n)
	assert.Equal(t, int64(11), rw.BytesWritten())
	assert.Equal(t, http.StatusOK, rw.StatusCode())
	assert.NoError(t, rw.Error())
}

type errReaderFrom struct {
	http.ResponseWriter
	err error
}

func (e errReaderFrom) ReadFrom(io.Reader) (int64, error) {
	return 0, e.err
}

func TestRespWriterReadFromError(t *testing.T) {
	want := errors.New("readfrom failed")
	rw := NewRespWriterWrapper(errReaderFrom{
		ResponseWriter: &httptest.ResponseRecorder{},
		err:            want,
	}, func(int64) {})

	_, err := rw.ReadFrom(strings.NewReader(strings.Repeat("a", 2*sniffLen)))
	require.ErrorIs(t, err, want)
	_, err = rw.Write([]byte("world"))
	require.NoError(t, err)

	assert.ErrorIs(t, rw.Error(), want)
	assert.Equal(t, http.StatusOK, rw.StatusCode())
}

type readerFromRecorder struct {
	*httptest.ResponseRecorder
	readFromBytes int64
}

func (r *readerFromRecorder) ReadFrom(src io.Reader) (int64, error) {
	n, err := io.Copy(r.ResponseRecorder, src)
	r.readFromBytes += n
	return n, err
}

func TestRespWriterReadFromEmptyKeepsHeaderUncommitted(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		rw := NewRespWriterWrapper(w, func(int64) {})
		n, err := rw.ReadFrom(strings.NewReader(""))
		assert.NoError(t, err)
		assert.Zero(t, n)

		rw.Header().Set("Retry-After", "5")
		rw.WriteHeader(http.StatusServiceUnavailable)
	}))
	defer srv.Close()

	req, err := http.NewRequestWithContext(t.Context(), http.MethodGet, srv.URL, http.NoBody)
	require.NoError(t, err)
	resp, err := srv.Client().Do(req)
	require.NoError(t, err)
	defer resp.Body.Close()

	assert.Equal(t, http.StatusServiceUnavailable, resp.StatusCode)
	assert.Equal(t, "5", resp.Header.Get("Retry-After"))
}

func TestRespWriterReadFromReadErrorKeepsHeaderUncommitted(t *testing.T) {
	want := errors.New("read failed")
	rec := httptest.NewRecorder()
	rw := NewRespWriterWrapper(&readerFromRecorder{ResponseRecorder: rec}, func(int64) {})

	_, err := rw.ReadFrom(iotest.ErrReader(want))
	require.ErrorIs(t, err, want)
	assert.ErrorIs(t, rw.Error(), want)

	rw.WriteHeader(http.StatusServiceUnavailable)
	assert.Equal(t, http.StatusServiceUnavailable, rec.Code)
	assert.Equal(t, http.StatusServiceUnavailable, rw.StatusCode())
}

func TestRespWriterReadFromUsesUnderlyingReadFrom(t *testing.T) {
	rec := httptest.NewRecorder()
	rf := &readerFromRecorder{ResponseRecorder: rec}
	var onWrite int64
	rw := NewRespWriterWrapper(rf, func(n int64) { onWrite += n })

	n, err := rw.ReadFrom(strings.NewReader(strings.Repeat("a", 2*sniffLen)))
	require.NoError(t, err)

	assert.Equal(t, int64(2*sniffLen), n)
	assert.Equal(t, int64(2*sniffLen), rw.BytesWritten())
	assert.Equal(t, int64(2*sniffLen), onWrite)
	assert.Equal(t, int64(sniffLen), rf.readFromBytes, "bytes after the prefix use the underlying ReadFrom")
	assert.Equal(t, 2*sniffLen, rec.Body.Len())
	assert.Equal(t, http.StatusOK, rec.Code)
}
