services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.157.0@sha256:f2f01157055a9b2aab9df7118e1f1c9abf345e99b23bc7a2bc791db374a7d0f6
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
      - ./strategies.json:/etc/strategies.json
    ports:
      - "5778:5778"  # default jaeger remote sampling port
