services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.160.0@sha256:799dc6cf12c96192af37b5bdba804da8c10b3bc563b43cb90c3f3c58d9572ad6
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
      - ./strategies.json:/etc/strategies.json
    ports:
      - "5778:5778"  # default jaeger remote sampling port
