version: "3"
services:

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
      - ./strategies.json:/etc/strategies.json
    ports:
      - "5778:5778"  # default jaeger remote sampling port
