services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.156.0@sha256:125bdbeb7590cc1952c5b3430ecf14063568980c2c93d5b38676cc0446ed8108
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
      - ./strategies.json:/etc/strategies.json
    ports:
      - "5778:5778"  # default jaeger remote sampling port
