# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
version: "3.7"
services:
  gin-client:
    image: golang:alpine
    networks:
      - example
    command:
      - "/bin/sh"
      - "-c"
      - "wget http://gin-server:8080/users/123 && cat 123"
    depends_on:
      - gin-server
  gin-server:
    build:
      dockerfile: $PWD/Dockerfile
      context: ../../../../../../
    ports:
      - "8080:8080"
    command:
      - "/bin/sh"
      - "-c"
      - "/go/bin/server"
    networks:
      - example
networks:
  example:
