# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
version: "3.7"
services:
  echo-client:
    image: golang:1.27.1-alpine@sha256:3f6d04dc61331ee3c2fbbaad62d54412a84680f6a041d269a20a5270a078515b
    networks:
      - example
    command:
      - "/bin/sh"
      - "-c"
      - "wget http://echo-server:8080/users/123 && cat 123"
    depends_on:
      - echo-server
  echo-server:
    build:
      dockerfile: $PWD/Dockerfile
      context: ../../../../../../
    ports:
      - "8080:80"
    command:
      - "/bin/sh"
      - "-c"
      - "/go/bin/server"
    networks:
      - example
networks:
  example:
