# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
version: "3.7"
services:
  aws-sdk-client:
    build:
      dockerfile: $PWD/Dockerfile
      context: ../../../../../..
    ports:
      - "8080:80"
    command:
      - "/bin/sh"
      - "-c"
      - "/go/bin/main"
    volumes:
      - ~/.aws:/root/.aws
    networks:
      - example
networks:
  example:
