// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// DO NOT MODIFY. Generated by gotmpl.
// source: internal/shared/logutil/convert_test.go.tmpl

package otellogrus

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/otel/attribute"
)

type testStringer struct {
	value any
}

func (testStringer) String() string {
	return "formatted"
}

func TestConvertValue(t *testing.T) {
	for _, tt := range []struct {
		name      string
		value     any
		wantValue attribute.Value
	}{
		{
			name:      "bool",
			value:     true,
			wantValue: attribute.BoolValue(true),
		},
		{
			name:      "string",
			value:     "value",
			wantValue: attribute.StringValue("value"),
		},
		{
			name:      "int",
			value:     10,
			wantValue: attribute.Int64Value(10),
		},
		{
			name:      "int8",
			value:     int8(127),
			wantValue: attribute.Int64Value(127),
		},
		{
			name:      "int16",
			value:     int16(32767),
			wantValue: attribute.Int64Value(32767),
		},
		{
			name:      "int32",
			value:     int32(2147483647),
			wantValue: attribute.Int64Value(2147483647),
		},
		{
			name:      "int64",
			value:     int64(9223372036854775807),
			wantValue: attribute.Int64Value(9223372036854775807),
		},
		{
			name:      "uint",
			value:     uint(42),
			wantValue: attribute.Int64Value(42),
		},
		{
			name:      "uint8",
			value:     uint8(255),
			wantValue: attribute.Int64Value(255),
		},
		{
			name:      "uint16",
			value:     uint16(65535),
			wantValue: attribute.Int64Value(65535),
		},
		{
			name:      "uint32",
			value:     uint32(4294967295),
			wantValue: attribute.Int64Value(4294967295),
		},
		{
			name:      "uint64",
			value:     uint64(9223372036854775807),
			wantValue: attribute.Int64Value(9223372036854775807),
		},
		{
			name:      "uint64-max",
			value:     uint64(18446744073709551615),
			wantValue: attribute.StringValue("18446744073709551615"),
		},
		{
			name:      "uintptr",
			value:     uintptr(12345),
			wantValue: attribute.Int64Value(12345),
		},
		{
			name:      "float64",
			value:     float64(3.14159),
			wantValue: attribute.Float64Value(3.14159),
		},
		{
			name:      "time.Duration",
			value:     time.Second,
			wantValue: attribute.Int64Value(1_000_000_000),
		},
		{
			name:      "complex64",
			value:     complex64(complex(float32(1), float32(2))),
			wantValue: attribute.MapValue(attribute.Float64("r", 1), attribute.Float64("i", 2)),
		},
		{
			name:      "complex128",
			value:     complex(float64(3), float64(4)),
			wantValue: attribute.MapValue(attribute.Float64("r", 3), attribute.Float64("i", 4)),
		},
		{
			name:      "time.Time",
			value:     time.Unix(1000, 1000),
			wantValue: attribute.Int64Value(time.Unix(1000, 1000).UnixNano()),
		},
		{
			name:      "[]byte",
			value:     []byte("hello"),
			wantValue: attribute.ByteSliceValue([]byte("hello")),
		},
		{
			name:      "error",
			value:     errors.New("test error"),
			wantValue: attribute.StringValue("test error"),
		},
		{
			name:      "error",
			value:     errors.New("test error"),
			wantValue: attribute.StringValue("test error"),
		},
		{
			name:      "error-nested",
			value:     fmt.Errorf("test error: %w", errors.New("nested error")),
			wantValue: attribute.StringValue("test error: nested error"),
		},
		{
			name:      "nil",
			value:     nil,
			wantValue: attribute.Value{},
		},
		{
			name:      "nil_ptr",
			value:     (*int)(nil),
			wantValue: attribute.Value{},
		},
		{
			name:      "int_ptr",
			value:     func() *int { i := 93; return &i }(),
			wantValue: attribute.Int64Value(93),
		},
		{
			name:      "string_ptr",
			value:     func() *string { s := "hello"; return &s }(),
			wantValue: attribute.StringValue("hello"),
		},
		{
			name:      "bool_ptr",
			value:     func() *bool { b := true; return &b }(),
			wantValue: attribute.BoolValue(true),
		},
		{
			name:      "int_empty_array",
			value:     []int{},
			wantValue: attribute.SliceValue([]attribute.Value{}...),
		},
		{
			name:  "int_array",
			value: []int{1, 2, 3},
			wantValue: attribute.SliceValue([]attribute.Value{
				attribute.Int64Value(1),
				attribute.Int64Value(2),
				attribute.Int64Value(3),
			}...),
		},
		{
			name:  "key_value_map",
			value: map[string]int{"one": 1},
			wantValue: attribute.MapValue(
				attribute.Int64("one", 1),
			),
		},
		{
			name:  "int_string_map",
			value: map[int]string{1: "one"},
			wantValue: attribute.MapValue(
				attribute.String("1", "one"),
			),
		},
		{
			name:  "nested_map",
			value: map[string]map[string]int{"nested": {"one": 1}},
			wantValue: attribute.MapValue(
				attribute.Map(
					"nested",
					attribute.Int64("one", 1),
				),
			),
		},
		{
			name: "struct_key_map",
			value: map[struct{ Name string }]int{
				{Name: "John"}: 42,
			},
			wantValue: attribute.MapValue(
				attribute.Int64("{Name:John}", 42),
			),
		},
		{
			name: "struct",
			value: struct {
				Name string
				Age  int
			}{
				Name: "John",
				Age:  42,
			},
			wantValue: attribute.StringValue("{Name:John Age:42}"),
		},
		{
			name: "struct_ptr",
			value: &struct {
				Name string
				Age  int
			}{
				Name: "John",
				Age:  42,
			},
			wantValue: attribute.StringValue("{Name:John Age:42}"),
		},
		{
			name: "nil_struct_ptr",
			value: (*struct {
				Name string
				Age  int
			})(nil),
			wantValue: attribute.Value{},
		},
		{
			name:      "ctx",
			value:     context.Background(), //nolint:usetesting // Verify background context conversion.
			wantValue: attribute.StringValue("context.Background"),
		},
		{
			name:      "standard attribute",
			value:     attribute.StringSliceValue([]string{"foo", "bar"}),
			wantValue: attribute.StringSliceValue([]string{"foo", "bar"}),
		},
		{
			name:      "attribute value",
			value:     attribute.SliceValue(attribute.StringValue("foo"), attribute.Int64Value(123)),
			wantValue: attribute.SliceValue(attribute.StringValue("foo"), attribute.Int64Value(123)),
		},
		{
			name:      "unhandled type",
			value:     chan int(nil),
			wantValue: attribute.StringValue("unhandled: (chan int) <nil>"),
		},
	} {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.wantValue, convertValue(tt.value))
		})
	}
}

func TestConvertValueFloat32(t *testing.T) {
	value := convertValue(float32(3.14))
	want := attribute.Float64Value(3.14)

	assert.InDelta(t, value.AsFloat64(), want.AsFloat64(), 0.0001)
}

func TestConvertValueCycle(t *testing.T) {
	const cycle = "<cycle>"

	t.Run("Map", func(t *testing.T) {
		value := map[string]any{}
		value["self"] = value

		assert.Equal(t, attribute.MapValue(attribute.String("self", cycle)), convertValue(value))
	})

	t.Run("Slice", func(t *testing.T) {
		value := make([]any, 1)
		value[0] = value

		assert.Equal(t, attribute.SliceValue(attribute.StringValue(cycle)), convertValue(value))
	})

	t.Run("PointerInterface", func(t *testing.T) {
		var value any
		value = &value

		assert.Equal(t, attribute.StringValue(cycle), convertValue(value))
	})

	t.Run("MutualMaps", func(t *testing.T) {
		first := map[string]any{}
		second := map[string]any{}
		first["next"] = second
		second["next"] = first

		want := attribute.MapValue(attribute.Map("next", attribute.String("next", cycle)))
		assert.Equal(t, want, convertValue(first))
	})

	t.Run("MixedMapSlice", func(t *testing.T) {
		mapping := map[string]any{}
		slice := []any{mapping}
		mapping["slice"] = slice

		want := attribute.MapValue(attribute.Slice("slice", attribute.StringValue(cycle)))
		assert.Equal(t, want, convertValue(mapping))
	})

	t.Run("BranchingMap", func(t *testing.T) {
		value := map[string]any{}
		value["left"] = value
		value["right"] = value

		want := []attribute.KeyValue{
			attribute.String("left", cycle),
			attribute.String("right", cycle),
		}
		assert.ElementsMatch(t, want, convertValue(value).AsMap())
	})

	t.Run("BranchingSlice", func(t *testing.T) {
		value := make([]any, 2)
		value[0] = value
		value[1] = value

		want := attribute.SliceValue(attribute.StringValue(cycle), attribute.StringValue(cycle))
		assert.Equal(t, want, convertValue(value))
	})

	t.Run("Struct", func(t *testing.T) {
		type wrapper struct{ Value any }

		mapping := map[string]any{}
		value := wrapper{Value: mapping}
		mapping["wrapper"] = value

		assert.Equal(t, attribute.StringValue(cycle), convertValue(value))
		assert.Equal(
			t,
			attribute.MapValue(attribute.String("wrapper", cycle)),
			convertValue(mapping),
		)
	})

	t.Run("DeepPointer", func(t *testing.T) {
		const depth = 128
		values := make([]any, depth+1)
		for i := range depth {
			values[i] = &values[i+1]
		}
		values[depth] = &values[0]

		assert.Equal(t, attribute.StringValue(cycle), convertValue(values[0]))
	})

	t.Run("DeepSlice", func(t *testing.T) {
		const depth = 128
		value := make([]any, 1)
		current := value
		for range depth {
			next := make([]any, 1)
			current[0] = next
			current = next
		}
		current[0] = value

		want := attribute.StringValue(cycle)
		for range depth + 1 {
			want = attribute.SliceValue(want)
		}
		assert.Equal(t, want, convertValue(value))
	})

	t.Run("PointerArray", func(t *testing.T) {
		value := &[1]any{}
		value[0] = value

		assert.Equal(t, attribute.SliceValue(attribute.StringValue(cycle)), convertValue(value))
	})

	t.Run("NamedMap", func(t *testing.T) {
		type namedMap map[string]any

		value := namedMap{}
		value["self"] = value

		assert.Equal(t, attribute.MapValue(attribute.String("self", cycle)), convertValue(value))
	})

	t.Run("NamedSlice", func(t *testing.T) {
		type namedSlice []any

		value := make(namedSlice, 1)
		value[0] = value

		assert.Equal(t, attribute.SliceValue(attribute.StringValue(cycle)), convertValue(value))
	})

	t.Run("FormattedMapKey", func(t *testing.T) {
		type key struct{ Value any }

		cyclic := map[string]any{}
		cyclic["self"] = cyclic
		formattedKey := &key{Value: cyclic}
		value := map[*key]int{formattedKey: 42}

		assert.Equal(t, attribute.MapValue(attribute.Int64(cycle, 42)), convertValue(value))
	})

	t.Run("FormattedInterfaceMapKey", func(t *testing.T) {
		type key struct{ Value any }

		cyclic := map[string]any{}
		cyclic["self"] = cyclic
		formattedKey := &key{Value: cyclic}
		value := map[any]int{formattedKey: 42}

		assert.Equal(t, attribute.MapValue(attribute.Int64(cycle, 42)), convertValue(value))
	})

	t.Run("ReflectValue", func(t *testing.T) {
		value := map[string]any{}
		value["self"] = value

		assert.Equal(t, attribute.StringValue(cycle), convertValue(reflect.ValueOf(value)))
	})
}

func TestConvertValueCycleDetectionIsPathLocal(t *testing.T) {
	sharedMap := map[string]any{"one": 1}
	sharedSlice := []any{1}
	value := []any{sharedMap, sharedMap, sharedSlice, sharedSlice}
	want := attribute.SliceValue(
		attribute.MapValue(attribute.Int64("one", 1)),
		attribute.MapValue(attribute.Int64("one", 1)),
		attribute.SliceValue(attribute.Int64Value(1)),
		attribute.SliceValue(attribute.Int64Value(1)),
	)

	assert.Equal(t, want, convertValue(value))
}

func TestConvertValueDeepPointerPathIsLocal(t *testing.T) {
	value := any(42)
	for range 128 {
		value = func(v any) *any { return &v }(value)
	}
	want := attribute.SliceValue(attribute.Int64Value(42), attribute.Int64Value(42))

	assert.Equal(t, want, convertValue([]any{value, value}))
}

func TestConvertValueDeepContainerPathIsLocal(t *testing.T) {
	value := any(42)
	want := attribute.Int64Value(42)
	for range 128 {
		value = []any{value}
		want = attribute.SliceValue(want)
	}

	assert.Equal(t, attribute.SliceValue(want, want), convertValue([]any{value, value}))
}

func TestConvertValueOverlappingSlices(t *testing.T) {
	value := []any{42, nil}
	value[1] = value[:1]
	want := attribute.SliceValue(
		attribute.Int64Value(42),
		attribute.SliceValue(attribute.Int64Value(42)),
	)

	assert.Equal(t, want, convertValue(value))
}

func TestConvertValueEmptyOverlappingSlice(t *testing.T) {
	value := []any{nil}
	value[0] = value[:0]

	assert.Equal(t, attribute.SliceValue(attribute.SliceValue()), convertValue(value))
}

func TestConvertValueOverlappingPointers(t *testing.T) {
	value := &[2]any{42, nil}
	value[1] = &value[0]
	want := attribute.SliceValue(attribute.Int64Value(42), attribute.Int64Value(42))

	assert.Equal(t, want, convertValue(value))
}

func TestConvertValueSharedPointer(t *testing.T) {
	value := 42
	want := attribute.SliceValue(attribute.Int64Value(42), attribute.Int64Value(42))

	assert.Equal(t, want, convertValue([]any{&value, &value}))
}

func TestConvertValuePreservesSafeFormatting(t *testing.T) {
	t.Run("NestedPointer", func(t *testing.T) {
		type node struct{ Next *node }

		value := &node{}
		value.Next = value

		assert.Equal(t, attribute.StringValue(fmt.Sprintf("%+v", *value)), convertValue(value))
	})

	t.Run("Stringer", func(t *testing.T) {
		cyclic := map[string]any{}
		cyclic["self"] = cyclic

		assert.Equal(t, attribute.StringValue("formatted"), convertValue(testStringer{value: cyclic}))
	})

	t.Run("PromotedStringer", func(t *testing.T) {
		cyclic := map[string]any{}
		cyclic["self"] = cyclic
		value := struct {
			testStringer
			Value any
		}{Value: cyclic}

		assert.Equal(t, attribute.StringValue("formatted"), convertValue(value))
	})
}

func TestConvertValueNilCollections(t *testing.T) {
	assert.Equal(t, attribute.SliceValue(), convertValue([]int(nil)))
	assert.Equal(t, attribute.MapValue(), convertValue(map[string]int(nil)))
}
