// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// DO NOT MODIFY. Generated by gotmpl.
// source: internal/shared/logutil/convert_test.go.tmpl

package otellogr

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"go.opentelemetry.io/otel/attribute"
)

type observedError struct {
	calls *int
}

func (e observedError) Error() string {
	(*e.calls)++
	return "observed"
}

func TestConvertValue(t *testing.T) {
	for _, tt := range []struct {
		name      string
		value     any
		wantValue attribute.Value
	}{
		{
			name:      "bool",
			value:     true,
			wantValue: attribute.BoolValue(true),
		},
		{
			name:      "string",
			value:     "value",
			wantValue: attribute.StringValue("value"),
		},
		{
			name:      "int",
			value:     10,
			wantValue: attribute.Int64Value(10),
		},
		{
			name:      "int8",
			value:     int8(127),
			wantValue: attribute.Int64Value(127),
		},
		{
			name:      "int16",
			value:     int16(32767),
			wantValue: attribute.Int64Value(32767),
		},
		{
			name:      "int32",
			value:     int32(2147483647),
			wantValue: attribute.Int64Value(2147483647),
		},
		{
			name:      "int64",
			value:     int64(9223372036854775807),
			wantValue: attribute.Int64Value(9223372036854775807),
		},
		{
			name:      "uint",
			value:     uint(42),
			wantValue: attribute.Int64Value(42),
		},
		{
			name:      "uint8",
			value:     uint8(255),
			wantValue: attribute.Int64Value(255),
		},
		{
			name:      "uint16",
			value:     uint16(65535),
			wantValue: attribute.Int64Value(65535),
		},
		{
			name:      "uint32",
			value:     uint32(4294967295),
			wantValue: attribute.Int64Value(4294967295),
		},
		{
			name:      "uint64",
			value:     uint64(9223372036854775807),
			wantValue: attribute.Int64Value(9223372036854775807),
		},
		{
			name:      "uint64-max",
			value:     uint64(18446744073709551615),
			wantValue: attribute.StringValue("18446744073709551615"),
		},
		{
			name:      "uintptr",
			value:     uintptr(12345),
			wantValue: attribute.Int64Value(12345),
		},
		{
			name:      "float64",
			value:     float64(3.14159),
			wantValue: attribute.Float64Value(3.14159),
		},
		{
			name:      "time.Duration",
			value:     time.Second,
			wantValue: attribute.Int64Value(1_000_000_000),
		},
		{
			name:      "complex64",
			value:     complex64(complex(float32(1), float32(2))),
			wantValue: attribute.MapValue(attribute.Float64("r", 1), attribute.Float64("i", 2)),
		},
		{
			name:      "complex128",
			value:     complex(float64(3), float64(4)),
			wantValue: attribute.MapValue(attribute.Float64("r", 3), attribute.Float64("i", 4)),
		},
		{
			name:      "time.Time",
			value:     time.Unix(1000, 1000),
			wantValue: attribute.Int64Value(time.Unix(1000, 1000).UnixNano()),
		},
		{
			name:      "[]byte",
			value:     []byte("hello"),
			wantValue: attribute.ByteSliceValue([]byte("hello")),
		},
		{
			name:      "error",
			value:     errors.New("test error"),
			wantValue: attribute.StringValue("test error"),
		},
		{
			name:      "error",
			value:     errors.New("test error"),
			wantValue: attribute.StringValue("test error"),
		},
		{
			name:      "error-nested",
			value:     fmt.Errorf("test error: %w", errors.New("nested error")),
			wantValue: attribute.StringValue("test error: nested error"),
		},
		{
			name:      "nil",
			value:     nil,
			wantValue: attribute.Value{},
		},
		{
			name:      "nil_ptr",
			value:     (*int)(nil),
			wantValue: attribute.Value{},
		},
		{
			name:      "int_ptr",
			value:     func() *int { i := 93; return &i }(),
			wantValue: attribute.Int64Value(93),
		},
		{
			name:      "string_ptr",
			value:     func() *string { s := "hello"; return &s }(),
			wantValue: attribute.StringValue("hello"),
		},
		{
			name:      "bool_ptr",
			value:     func() *bool { b := true; return &b }(),
			wantValue: attribute.BoolValue(true),
		},
		{
			name:      "int_empty_array",
			value:     []int{},
			wantValue: attribute.SliceValue([]attribute.Value{}...),
		},
		{
			name:  "int_slice",
			value: []int{1, 2, 3},
			wantValue: attribute.SliceValue([]attribute.Value{
				attribute.Int64Value(1),
				attribute.Int64Value(2),
				attribute.Int64Value(3),
			}...),
		},
		{
			name:  "int_array",
			value: [3]int{1, 2, 3},
			wantValue: attribute.SliceValue([]attribute.Value{
				attribute.Int64Value(1),
				attribute.Int64Value(2),
				attribute.Int64Value(3),
			}...),
		},
		{
			name:  "key_value_map",
			value: map[string]int{"one": 1},
			wantValue: attribute.MapValue(
				attribute.Int64("one", 1),
			),
		},
		{
			name:  "int_string_map",
			value: map[int]string{1: "one"},
			wantValue: attribute.MapValue(
				attribute.String("1", "one"),
			),
		},
		{
			name:  "nested_map",
			value: map[string]map[string]int{"nested": {"one": 1}},
			wantValue: attribute.MapValue(
				attribute.Map(
					"nested",
					attribute.Int64("one", 1),
				),
			),
		},
		{
			name: "struct_key_map",
			value: map[struct{ Name string }]int{
				{Name: "John"}: 42,
			},
			wantValue: attribute.MapValue(
				attribute.Int64("{Name:John}", 42),
			),
		},
		{
			name: "struct",
			value: struct {
				Name string
				Age  int
			}{
				Name: "John",
				Age:  42,
			},
			wantValue: attribute.StringValue("{Name:John Age:42}"),
		},
		{
			name: "struct_ptr",
			value: &struct {
				Name string
				Age  int
			}{
				Name: "John",
				Age:  42,
			},
			wantValue: attribute.StringValue("{Name:John Age:42}"),
		},
		{
			name: "nil_struct_ptr",
			value: (*struct {
				Name string
				Age  int
			})(nil),
			wantValue: attribute.Value{},
		},
		{
			name:      "ctx",
			value:     context.Background(), //nolint:usetesting // Verify background context conversion.
			wantValue: attribute.StringValue("context.Background"),
		},
		{
			name:      "standard attribute",
			value:     attribute.StringSliceValue([]string{"foo", "bar"}),
			wantValue: attribute.StringSliceValue([]string{"foo", "bar"}),
		},
		{
			name:      "attribute value",
			value:     attribute.SliceValue(attribute.StringValue("foo"), attribute.Int64Value(123)),
			wantValue: attribute.SliceValue(attribute.StringValue("foo"), attribute.Int64Value(123)),
		},
		{
			name:      "unhandled type",
			value:     chan int(nil),
			wantValue: attribute.StringValue("unhandled: (chan int) <nil>"),
		},
	} {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.wantValue, convertValue(tt.value))
			assert.Equal(
				t,
				attribute.SliceValue(tt.wantValue),
				convertValue([]any{tt.value}),
				"nested conversion",
			)
		})
	}
}

func TestConvertValueFloat32(t *testing.T) {
	value := convertValue(float32(3.14))
	want := attribute.Float64Value(3.14)

	assert.InDelta(t, value.AsFloat64(), want.AsFloat64(), 0.0001)

	nested := convertValue([]any{float32(3.14)}).AsSlice()
	require.Len(t, nested, 1)
	assert.InDelta(t, nested[0].AsFloat64(), want.AsFloat64(), 0.0001)
}

func TestConvertValueRecursiveValues(t *testing.T) {
	directMap := map[string]any{}
	directMap["self"] = directMap

	directSlice := make([]any, 1)
	directSlice[0] = directSlice

	var pointerInterface any
	pointerInterface = &pointerInterface

	var mutualLeft any
	var mutualRight any
	mutualLeft = &mutualRight
	mutualRight = &mutualLeft

	mixedMap := map[string]any{}
	mixedSlice := []any{mixedMap}
	mixedMap["slice"] = mixedSlice

	branchingSlice := make([]any, 2)
	branchingSlice[0] = branchingSlice
	branchingSlice[1] = branchingSlice

	for _, tt := range []struct {
		name  string
		value any
	}{
		{name: "direct map cycle", value: directMap},
		{name: "direct slice cycle", value: directSlice},
		{name: "pointer-interface cycle", value: pointerInterface},
		{name: "mutual pointer-interface cycle", value: mutualLeft},
		{name: "mixed map-slice cycle", value: mixedMap},
		{name: "branching slice cycle", value: branchingSlice},
	} {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, attribute.StringValue(maxDepthExceeded), convertValue(tt.value))
		})
	}
}

func TestConvertValueDepthLimit(t *testing.T) {
	t.Run("100 nested slices ending in scalar succeed", func(t *testing.T) {
		got := convertValue(wrapSlices(maxConvertDepth, "leaf"))
		leaf := requireNestedSlice(t, got)
		assert.Equal(t, attribute.StringValue("leaf"), leaf)
	})

	t.Run("101 nested slices exceed limit", func(t *testing.T) {
		got := convertValue(wrapSlices(maxConvertDepth+1, "leaf"))
		assert.Equal(t, attribute.StringValue(maxDepthExceeded), got)
	})

	t.Run("interface indirection does not count toward limit", func(t *testing.T) {
		got := convertValue(wrapSlices(maxConvertDepth-1, []any{"leaf"}))
		leaf := requireNestedSlice(t, got)
		assert.Equal(t, attribute.StringValue("leaf"), leaf)
	})

	t.Run("container beyond limit fails through interface", func(t *testing.T) {
		got := convertValue(wrapSlices(maxConvertDepth-1, []any{[]any{"leaf"}}))
		assert.Equal(t, attribute.StringValue(maxDepthExceeded), got)
	})

	t.Run("100 pointers ending in scalar succeed", func(t *testing.T) {
		got := convertValue(wrapPointers(maxConvertDepth, "leaf"))
		assert.Equal(t, attribute.StringValue("leaf"), got)
	})

	t.Run("101 pointers exceed limit", func(t *testing.T) {
		got := convertValue(wrapPointers(maxConvertDepth+1, "leaf"))
		assert.Equal(t, attribute.StringValue(maxDepthExceeded), got)
	})

	t.Run("nil is allowed at boundary", func(t *testing.T) {
		got := convertValue(wrapPointers(maxConvertDepth, (*int)(nil)))
		assert.Equal(t, attribute.Value{}, got)
	})

	t.Run("empty slice is allowed at boundary", func(t *testing.T) {
		got := convertValue(wrapSlices(maxConvertDepth, []any{}))
		empty := requireNestedSlice(t, got)
		assert.Equal(t, attribute.SliceValue(), empty)
	})

	t.Run("empty map is allowed at boundary", func(t *testing.T) {
		got := convertValue(wrapSlices(maxConvertDepth, map[string]any{}))
		empty := requireNestedSlice(t, got)
		assert.Equal(t, attribute.MapValue(), empty)
	})
}

func TestConvertValueFailsFast(t *testing.T) {
	calls := 0
	value := make([]any, 2)
	value[0] = value
	value[1] = observedError{calls: &calls}

	assert.Equal(t, attribute.StringValue(maxDepthExceeded), convertValue(value))
	assert.Zero(t, calls, "conversion continued after the depth limit")
}

func TestConvertValueSharedAcyclicValues(t *testing.T) {
	sharedMap := map[string]any{"one": 1}
	sharedSlice := []any{"two"}
	value := []any{sharedMap, sharedMap, sharedSlice, sharedSlice}

	wantMap := attribute.MapValue(attribute.Int64("one", 1))
	wantSlice := attribute.SliceValue(attribute.StringValue("two"))
	want := attribute.SliceValue(wantMap, wantMap, wantSlice, wantSlice)
	assert.Equal(t, want, convertValue(value))
}

func wrapSlices(depth int, leaf any) any {
	value := reflect.ValueOf(leaf)
	for range depth {
		slice := reflect.MakeSlice(reflect.SliceOf(value.Type()), 1, 1)
		slice.Index(0).Set(value)
		value = slice
	}
	return value.Interface()
}

func wrapPointers(depth int, leaf any) any {
	value := reflect.ValueOf(leaf)
	for range depth {
		pointer := reflect.New(value.Type())
		pointer.Elem().Set(value)
		value = pointer
	}
	return value.Interface()
}

func requireNestedSlice(t *testing.T, value attribute.Value) attribute.Value {
	t.Helper()
	for range maxConvertDepth {
		require.Equal(t, attribute.SLICE, value.Type())
		values := value.AsSlice()
		require.Len(t, values, 1)
		value = values[0]
	}
	return value
}
