# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
version: "3.7"
services:
  go-restful-client:
    image: golang:1.24-alpine
    networks:
      - example
    command:
      - "/bin/sh"
      - "-c"
      - "wget -O - http://go-restful-server:8080/users/123"
    depends_on:
      - go-restful-server
  go-restful-server:
    build:
      dockerfile: $PWD/Dockerfile
      context: ../../../../../..
    ports:
      - "8080:80"
    command:
      - "/bin/sh"
      - "-c"
      - "/go/bin/server"
    networks:
      - example
networks:
  example:
