#!/usr/bin/env bash
# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# Runs weaver registry live-check against E2E telemetry generated by
# the instrumentation libraries in this repository.
#
# Usage: ./tools/weaver-live-check.sh
#
# See https://github.com/open-telemetry/weaver/blob/main/crates/weaver_live_check/README.md

set -euo pipefail

WEAVER_VERSION="${WEAVER_VERSION:-v0.23.0}"

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)
case "${ARCH}" in
    arm64|aarch64) ARCH="aarch64" ;;
    x86_64)        ARCH="x86_64"  ;;
esac
case "${OS}" in
    darwin) OS="apple-darwin"       ;;
    linux)  OS="unknown-linux-gnu"  ;;
esac

WEAVER_ARCHIVE="weaver-${ARCH}-${OS}.tar.xz"
WEAVER_URL="https://github.com/open-telemetry/weaver/releases/download/${WEAVER_VERSION}/${WEAVER_ARCHIVE}"

TOOLS_DIR="$(pwd)/.tools"
mkdir -p "${TOOLS_DIR}"

if [ ! -x "${TOOLS_DIR}/weaver" ] || ! "${TOOLS_DIR}/weaver" --version 2>/dev/null | grep -q "${WEAVER_VERSION#v}"; then
    echo "Downloading weaver ${WEAVER_VERSION}..."
    tmpdir=$(mktemp -d)
    curl -sL "${WEAVER_URL}" -o "${tmpdir}/${WEAVER_ARCHIVE}"
    tar -xf "${tmpdir}/${WEAVER_ARCHIVE}" -C "${tmpdir}"
    found=$(find "${tmpdir}" -type f -name weaver | head -n 1)
    if [ -z "${found}" ]; then
        echo "ERROR: weaver binary not found in archive" >&2
        exit 1
    fi
    mv "${found}" "${TOOLS_DIR}/weaver"
    chmod +x "${TOOLS_DIR}/weaver"
    rm -rf "${tmpdir}"
fi

REPORTS_DIR="$(pwd)/weaver-reports"
mkdir -p "${REPORTS_DIR}"

# Start weaver live-check in the background (CI/CD pattern from weaver README).
"${TOOLS_DIR}/weaver" registry live-check --format json --output "${REPORTS_DIR}" &
WEAVER_PID=$!

# Wait for the OTLP receiver to be ready.
timeout=60
while ! nc -z localhost 4317 2>/dev/null; do
    sleep 1
    timeout=$((timeout - 1))
    if [ "${timeout}" -eq 0 ]; then
        echo "ERROR: timed out waiting for weaver OTLP listener" >&2
        kill -9 "${WEAVER_PID}" 2>/dev/null || true
        exit 1
    fi
done

# Run the E2E telemetry generator that exercises instrumentation libraries.
(cd internal/e2e/weaver && go run .)

# Stop weaver and capture its exit code.
kill -HUP "${WEAVER_PID}" 2>/dev/null || true
wait "${WEAVER_PID}" && weaver_rc=0 || weaver_rc=$?

echo "weaver exit code: ${weaver_rc}"
echo "Reports saved to ${REPORTS_DIR}"

# Warn-only: always exit 0 until all instrumentations achieve full semconv compliance.
exit 0
