name: dependabot-pr

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "~1.21.3"
          check-latest: true
          cache-dependency-path: "**/go.sum"

      - name: Install zsh
        run: sudo apt-get update; sudo apt-get install zsh

      - name: Run dependabot-pr.sh
        run: ./.github/workflows/scripts/dependabot-pr.sh
        env:
          GITHUB_TOKEN: ${{ secrets.OPENTELEMETRYBOT_GITHUB_TOKEN }}
