name: OSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: "4 22 * * 1" # once a week
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    permissions:
      contents: read # for actions/checkout
      id-token: write # for Scorecard to publish results
      security-events: write # for the SARIF upload to code scanning
    uses: open-telemetry/shared-workflows/.github/workflows/scorecard.yml@71c77e7624e3dccefec108b135186c22e5d9d69b # v0.9.0
